Controllers/ShippingManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Nop.Core;
using Nop.Core.Domain.Directory;
using Nop.Core.Domain.Shipping;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Shipping;
using Nop.Services.Stores;
using Nop.Services.Vendors;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Models.Extensions;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

using Nop.Plugin.Shipping.Manager.Domain;
using Nop.Plugin.Shipping.Manager.Models;
using Nop.Plugin.Shipping.Manager.Services;
using Nop.Plugin.Shipping.Manager.Settings;
using Nop.Plugin.Shipping.Manager.ExportImport;

using Nop.Plugin.Apollo.Integrator;
using Nop.Plugin.Apollo.Integrator.Services;

namespace Nop.Plugin.Shipping.Manager.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.ADMIN)]
    public class ShippingManagerController : BasePluginController
    {

        #region Fields

        protected readonly CurrencySettings _currencySettings;
        protected readonly ShippingManagerSettings _shippingManagerSettings;
        protected readonly ICountryService _countryService;
        protected readonly ICurrencyService _currencyService;
        protected readonly ILocalizationService _localizationService;
        protected readonly IMeasureService _measureService;
        protected readonly IPermissionService _permissionService;
        protected readonly ISettingService _settingService;
        protected readonly IStateProvinceService _stateProvinceService;
        protected readonly IStoreService _storeService;
        protected readonly MeasureSettings _measureSettings;
        protected readonly IShippingService _shippingService;
        protected readonly IShippingManagerService _shippingManagerService;
        protected readonly ICarrierService _carrierService;
        protected readonly INotificationService _notificationService;
        protected readonly IStoreContext _storeContext;
        protected readonly IWorkContext _workContext;
        protected readonly IEntityGroupService _entityGroupService;
        protected readonly IShippingManagerInstallService _shippingManagerInstallService;
        protected readonly ILogger _logger;
        protected readonly IVendorService _vendorService;
        protected readonly IExportImportManager _exportImportManager;
        protected readonly ISendcloudService _sendcloudService;
        protected readonly IFastwayService _fastwayService;
        protected readonly ShippingSettings _shippingSettings;
        protected readonly IGenericAttributeService _genericAttributeService;

        SystemHelper _systemHelper = new SystemHelper();

        #endregion

        #region Ctor

        public ShippingManagerController(CurrencySettings currencySettings,
            ShippingManagerSettings shippingManagerSettings,
            ICountryService countryService,
            ICurrencyService currencyService,
            ILocalizationService localizationService,
            IMeasureService measureService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStateProvinceService stateProvinceService,
            IStoreService storeService,
            MeasureSettings measureSettings,
            IShippingService shippingService,
            IShippingManagerService shippingManagerService,
            ICarrierService carrierService,
            INotificationService notificationService,
            IStoreContext storeContext,
            IWorkContext workContext,
            IEntityGroupService entityGroupService,
            IShippingManagerInstallService shippingManagerInstallService,
            ILogger logger,
            IVendorService vendorService,
            IExportImportManager exportImportManager,
            ISendcloudService sendcloudService,
            IFastwayService fastwayService,
            ShippingSettings shippingSettings,
            IGenericAttributeService genericAttributeService)
        {
            _currencySettings = currencySettings;
            _shippingManagerSettings = shippingManagerSettings;
            _countryService = countryService;
            _currencyService = currencyService;
            _localizationService = localizationService;
            _measureService = measureService;
            _permissionService = permissionService;
            _settingService = settingService;
            _stateProvinceService = stateProvinceService;
            _storeService = storeService;
            _measureSettings = measureSettings;
            _shippingService = shippingService;
            _shippingManagerService = shippingManagerService;
            _carrierService = carrierService;
            _notificationService = notificationService;
            _storeContext = storeContext;
            _workContext = workContext;
            _entityGroupService = entityGroupService;
            _shippingManagerInstallService = shippingManagerInstallService;
            _logger = logger;
            _vendorService = vendorService;
            _exportImportManager = exportImportManager;
            _sendcloudService = sendcloudService;
            _fastwayService = fastwayService;
            _shippingSettings = shippingSettings;
            _genericAttributeService = genericAttributeService;
        }

        #endregion

        #region Manage Methods

        public async Task<IActionResult> Manage()
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Manage))
                return AccessDeniedView();

            //Get vendor
            int vendorId = await _entityGroupService.GetActiveVendorScopeAsync();

            var model = new ShippingManagerModel
            {
                LimitMethodsToCreated = _shippingManagerSettings.LimitMethodsToCreated,
                ReturnValidOptionsIfThereAreAny = _shippingSettings.ReturnValidOptionsIfThereAreAny,
                ShippingByWeightByTotalEnabled = _shippingManagerSettings.ShippingByWeightByTotalEnabled,
                DisplayVendor = vendorId == 0
            };

            //stores
            model.AvailableStores.Add(new SelectListItem { Text = "*", Value = "0" });
            foreach (var store in await _storeService.GetAllStoresAsync())
                model.AvailableStores.Add(new SelectListItem { Text = store.Name, Value = store.Id.ToString() });

            //warehouses
            model.AvailableWarehouses.Add(new SelectListItem { Text = "*", Value = "0" });
            foreach (var warehouses in await _shippingService.GetAllWarehousesAsync())
                model.AvailableWarehouses.Add(new SelectListItem { Text = warehouses.Name, Value = warehouses.Id.ToString() });

            //carriers
            model.AvailableCarriers = await _shippingManagerService.PrepareAvailableCarriersModelAsync(true);

            //shipping methods
            int index = 0;
            (model.AvailableShippingMethods, index) = await _shippingManagerService.PrepareAvailableShippingMethodsModelAsync(true);

            //countries
            if (!_shippingManagerSettings.InternationalOperationsEnabled)
            {
                //prepare available states
                model.AvailableStates.Add(new SelectListItem { Text = "*", Value = "0" });
                var states = (await _stateProvinceService.GetStateProvincesByCountryIdAsync(_shippingManagerSettings.DefaultCountryId)).ToList();
                var result = new List<SelectListItem>();
                foreach (var state in states)
                {
                    model.AvailableStates.Add(new SelectListItem
                    {
                        Value = state.Id.ToString(),
                        Text = await _localizationService.GetLocalizedAsync(state, x => x.Name)
                    });
                }
            }
            else
            {
                //prepare available countries
                var countries = await _countryService.GetAllCountriesAsync();
                model.AvailableCountries.Add(new SelectListItem { Text = "*", Value = "0" });
                foreach (var c in countries)
                    model.AvailableCountries.Add(new SelectListItem { Text = c.Name, Value = c.Id.ToString() });

                //states
                model.AvailableStates.Add(new SelectListItem { Text = "*", Value = "0" });
            }

            model.SetGridPageSize();
            model.SearchActive = true;

            return View("~/Plugins/SSI.Shipping.Manager/Views/Manage.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(ShippingManagerModel model)
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Manage))
                return Content("Access denied");

            //save settings
            _shippingManagerSettings.LimitMethodsToCreated = model.LimitMethodsToCreated;
            _shippingSettings.ReturnValidOptionsIfThereAreAny = model.ReturnValidOptionsIfThereAreAny;

            await _settingService.SaveSettingAsync(_shippingManagerSettings);
            await _settingService.SaveSettingAsync(_shippingSettings);

            return Json(new { Result = true });
        }

        [HttpPost]
        public async Task<IActionResult> SaveMode(bool value)
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Manage))
                return Content("Access denied");

            //save settings
            _shippingManagerSettings.ShippingByWeightByTotalEnabled = value;

Views/AddRateByWeightByTotalPopup.cshtml
@model ShippingManagerByWeightByTotalModel

@{
    Layout = "_AdminPopupLayout";
}

<form asp-controller="ShippingManager" asp-action="AddRateByWeightByTotalPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Common.AddNew")
        </h1>
        <div class="float-right">
            <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/_CreateOrUpdateRateByWeightByTotal.cshtml", Model)
        </div>
    </div>
</form>

Views/EditRateByWeightByTotalPopup.cshtml
@model ShippingManagerByWeightByTotalModel

@{
    Layout = "_AdminPopupLayout";
}

<form asp-controller="ShippingManager" asp-action="EditRateByWeightByTotalPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Common.Edit")
        </h1>
        <div class="float-right">
            <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/_CreateOrUpdateRateByWeightByTotal.cshtml", Model)
        </div>
    </div>
</form>

Views/Manage.cshtml
@model ShippingManagerModel

@{
    Layout = "_AdminLayout";

    //page title
    ViewBag.Title = T("Plugins.Shipping.Manager.Manage").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Nop.Plugins.Shipping.Manager.Manage");
}

<form asp-controller="ShippingManager" asp-action="Manage" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Plugins.Shipping.Manager.Manage")
        </h1>
        <div class="float-right">
            <button type="button" name="importexcel" class="btn btn-success" data-toggle="modal" data-target="#importexcel-window">
                <i class="fas fa-upload"></i>
                @T("Admin.Common.Import")
            </button>
            <div class="btn-group">
                <button type="button" class="btn btn-success">
                    <i class="fas fa-download"></i>
                    @T("Admin.Common.Export")
                </button>
                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">&nbsp;</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <button type="submit" name="ExportRatesToExcel">
                            <i class="fas fa-file-excel-o"></i>
                            @T("Admin.Common.ExportToExcel.All")
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="form-horizontal">
            @await Component.InvokeAsync("VendorScopeConfiguration")
            <div class="cards-group">
                <div class="card card-default">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="onoffswitch">
                                    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="advanced-settings-mode" checked="@Model.ShippingByWeightByTotalEnabled">
                                    <label class="onoffswitch-label" for="advanced-settings-mode">
                                        <span class="onoffswitch-inner"
                                              data-locale-basic="@T("Plugins.Shipping.Manager.Fixed")"
                                              data-locale-advanced="@T("Plugins.Shipping.Manager.ShippingByWeight")"></span>
                                        <span class="onoffswitch-switch"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="float-right">
                                    <a asp-controller="ShippingOperations" asp-action="Methods" class="btn btn-primary">
                                        <i class="fas fa-truck"></i>
                                        @T("Admin.Configuration.Shipping.Methods.Manage")
                                    </a>
                                    @if (shippingManagerSettings.InternationalOperationsEnabled && !Model.ShippingByWeightByTotalEnabled)
                                    {
                                        <a asp-controller="ShippingOperations" asp-action="Restrictions" class="btn btn-primary">
                                            <i class="fa fa-globe"></i>
                                            @T("Admin.Configuration.Shipping.Restrictions")
                                        </a>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/_FixedRate.cshtml")
                    @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/_ByWeightByTotal.cshtml", Model)
                </div>
            </div>
        </div>
    </div>
</form>

<div id="importexcel-window" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="importexcel-window-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="importexcel-window-title">@T("Admin.Common.ImportFromExcel")</h4>
            </div>
            <form asp-controller="ShippingManager" asp-action="ImportRatesToExcel" method="post" enctype="multipart/form-data">
                <div class="form-horizontal">
                    <div class="modal-body">
                        <ul class="common-list">
                            <li>
                                <em>@T("Plugins.Shipping.Manager.ByWeightByTotal.ImportFromExcelTip")</em>
                            </li>
                            <li>
                                <em>@T("Admin.Common.ImportFromExcel.ManyRecordsWarning")</em>
                            </li>
                            <li style="color:#3c8dbc">@T("Plugins.Shipping.Manager.ByWeightByTotal.ExcelFileUploadTip")</li>
                            <li>
                                <a href="~/Plugins/SSI.Shipping.Manager/ExportImport/SampleTemplate.xlsx"><i class="fa fa-download" aria-hidden="true"></i>@T("Plugins.Shipping.Manager.ByWeightByTotal.SampleExcel")</a>
                            </li>
                        </ul>
                        <div class="form-group row">
                            <div class="col-md-2">
                                <div class="label-wrapper">
                                    <label class="control-label">
                                        @T("Admin.Common.ExcelFile")
                                    </label>
                                </div>
                            </div>
                            <div class="col-md-10">
                                <input type="file" id="importexcelfile" name="importexcelfile" class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">
                            @T("Admin.Common.ImportFromExcel")
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
function checkAdvancedSettingsMode(advanced) {
    if (advanced) {
        $("body").addClass("advanced-settings-mode");
        $("body").removeClass("basic-settings-mode");
    } else {
        $("body").removeClass("advanced-settings-mode");
        $("body").addClass("basic-settings-mode");
    }
}
checkAdvancedSettingsMode($("#advanced-settings-mode").is(':checked'));
$(document)
    .ready(function() {
        $("#advanced-settings-mode")
            .click(function() {
                checkAdvancedSettingsMode($(this).is(':checked'));
                $.ajax({
                    cache: false,
                    url: "@Url.Action("SaveMode", "ShippingManager")",
                    type: "POST",
                    data: {
                        value: $(this).is(':checked')
                    },
                    dataType: "json",
                    error: function (jqXHR, textStatus, errorThrown) {
                        $("#saveModeAlert").click();
                    }
                });
                ensureDataTablesRendered();
            });
    });
</script>

<nop-alert asp-alert-id="saveModeAlert" asp-alert-message="@T("Admin.Common.Alert.Save.Error")" />

Views/_CreateOrUpdateRateByWeightByTotal.cshtml
@model ShippingManagerByWeightByTotalModel
@using Nop.Web.Framework.Extensions

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />
<input asp-for="BtnId" type="hidden"/>

@{
    var hideInternationalOperations = "none";
    if (shippingManagerSettings.InternationalOperationsEnabled)
    {
        hideInternationalOperations = string.Empty;
    }
}

@if (ViewBag.RefreshPage == true)
{
    <script type="text/javascript">
        try
        {
            $("#@(ViewBag.BtnId)", window.opener.document).click();
        }
        catch (e)
        {
            Console.log(e);
        }
        window.close();
    </script>
}

<script>
    $(document).ready(function () {
        $("#@Html.IdFor(model => model.CountryId)").change(function () {
            var selectedItem = $(this).val();
            var ddlStates = $("#@Html.IdFor(model => model.StateProvinceId)");
            $.ajax({
                cache: false,
                type: "GET",
                url: "@(Url.Action("GetStatesByCountryId", "Country"))",
                data: {
                    "countryId": selectedItem,
                    "addAsterisk": "true"
                },
                success: function (data, textStatus, jqXHR) {
                    ddlStates.html('');
                    $.each(data, function (id, option) {
                        ddlStates.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#getStatesByCountryIdAlert").click();
                }
            });
        });
    });
</script>

<div class="cards-group">
    <div class="card card-default card-popup">
        <div class="card-body">
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="Active" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="Active" />
                    <span asp-validation-for="Active"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="DisplayOrder" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="DisplayOrder" />
                    <span asp-validation-for="DisplayOrder"></span>
                </div>
            </div>
            <div class="form-group row" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                <div class="col-sm-3">
                    <nop-label asp-for="StoreId" />
                </div>
                <div class="col-sm-6">
                    <nop-select asp-for="StoreId" asp-items="Model.AvailableStores" />
                    <span asp-validation-for="StoreId"></span>
                </div>
            </div>
            <div class="form-group row" @(Model.AvailableVendors.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                <div class="col-sm-3">
                    <nop-label asp-for="VendorId" />
                </div>
                <div class="col-sm-6">
                    <nop-select asp-for="VendorId" asp-items="Model.AvailableVendors" />
                    <span asp-validation-for="VendorId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="CarrierId" />
                </div>
                <div class="col-sm-6">
                    <nop-select asp-for="CarrierId" asp-items="Model.AvailableCarriers" />
                    <span asp-validation-for="CarrierId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="ShippingMethodId" />
                </div>
                <div class="col-sm-6">
                    <nop-select asp-for="ShippingMethodId" asp-items="Model.AvailableShippingMethods" />
                    <span asp-validation-for="ShippingMethodId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="FriendlyName" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="FriendlyName" />
                    <span asp-validation-for="FriendlyName"></span>
                </div>
            </div>
            <div class="form-group row" style="display:@hideInternationalOperations">
                <div class="col-sm-3">
                    <nop-label asp-for="SendFromAddressId" />
                </div>
                <div class="col-sm-6">
                    <nop-select asp-for="SendFromAddressId" asp-items="Model.AvailableSendFromAddress" />
                    <span asp-validation-for="SendFromAddressId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="WarehouseId" />
                </div>
                <div class="col-sm-6">
                    <nop-select asp-for="WarehouseId" asp-items="Model.AvailableWarehouses" />
                    <span asp-validation-for="WarehouseId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="CutOffTimeId" />
                </div>
                <div class="col-sm-6">
                    <nop-select asp-for="CutOffTimeId" asp-items="Model.AvailableCutOffTime" />
                    <span asp-validation-for="CutOffTimeId"></span>
                </div>
            </div>
            <div class="form-group row" style="display:@hideInternationalOperations">
                <div class="col-sm-3">
                    <nop-label asp-for="CountryId" />
                </div>
                <div class="col-sm-6">
                    <nop-select asp-for="CountryId" asp-items="Model.AvailableCountries" />
                    <span asp-validation-for="CountryId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="StateProvinceId" />
                </div>
                <div class="col-sm-6">
                    <nop-select asp-for="StateProvinceId" asp-items="Model.AvailableStates" />
                    <span asp-validation-for="StateProvinceId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="Zip" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="Zip" />
                    <span asp-validation-for="Zip"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="AdditionalFixedCost" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="AdditionalFixedCost" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                    <span asp-validation-for="AdditionalFixedCost"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="RatePerWeightUnit" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="RatePerWeightUnit" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                    <span asp-validation-for="RatePerWeightUnit"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="PercentageRateOfSubtotal" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="PercentageRateOfSubtotal" />
                    <span asp-validation-for="PercentageRateOfSubtotal"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="LowerWeightLimit" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="LowerWeightLimit" />
                    <span asp-validation-for="LowerWeightLimit"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="WeightFrom" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="WeightFrom" asp-postfix="@Model.BaseWeightIn" />
                    <span asp-validation-for="WeightFrom"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="WeightTo" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="WeightTo" asp-postfix="@Model.BaseWeightIn" />
                    <span asp-validation-for="WeightTo"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="CalculateCubicWeight" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="CalculateCubicWeight" />
                    <span asp-validation-for="CalculateCubicWeight"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="CubicWeightFactor" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="CubicWeightFactor" />
                    <span asp-validation-for="CubicWeightFactor"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="OrderSubtotalFrom" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="OrderSubtotalFrom" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                    <span asp-validation-for="OrderSubtotalFrom"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="OrderSubtotalTo" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="OrderSubtotalTo" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                    <span asp-validation-for="OrderSubtotalTo"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="TransitDays" />
                </div>
                <div class="col-sm-6">
                    <nop-editor asp-for="TransitDays" />
                    <span asp-validation-for="TransitDays"></span>
                </div>
            </div>
			<div class="form-group row">
				<div class="col-sm-3">
					<nop-label asp-for="Description" />
				</div>
				<div class="col-sm-6">
					<nop-editor asp-for="Description" />
					<span asp-validation-for="Description"></span>
				</div>
			</div>
        </div>
    </div>
</div>
<nop-alert asp-alert-id="getStatesByCountryIdAlert" asp-alert-message="@T("Admin.Common.Alert.States.Failed")" />