Models/EntityGroup/CustomerScopeConfigurationModel.cs
using System.Collections.Generic;
using Nop.Web.Areas.Admin.Models.Customers;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Apollo.Integrator.Models.EntityGroup
{

    public partial record CustomerList : BaseNopModel
    {
        #region Ctor

        public CustomerList()
        {
            EntityName = string.Empty;
        }

        #endregion

        #region Properties

        public int CustomerId { get; set; }

        public string EntityName { get; set; }

        #endregion
    }

    /// <summary>
    /// Represents a store scope configuration model
    /// </summary>
    public partial record CustomerScopeConfigurationModel : BaseNopModel
    {
        #region Ctor

        public CustomerScopeConfigurationModel()
        {
            Customers = new List<CustomerList>();
            CustomerGroupMembers = new List<CustomerList>();
        }

        #endregion

        #region Properties

        public bool IsSupervisor { get; set; }

        public int CustomerId { get; set; }

        public IList<CustomerList> Customers { get; set; }

        public int GroupCustomerId { get; set; }

        public IList<CustomerList> CustomerGroupMembers { get; set; }

        public bool DisplayControl { get; set; }

        public bool DisplayControlCustomerGroups { get; set; }

        #endregion
    }
}

Models/EntityGroup/EntityGroupListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Apollo.Integrator.Models.EntityGroup
{
    public partial record EntityGroupListModel : BasePagedListModel<EntityGroupModel>
    {
    }
}

Models/EntityGroup/EntityGroupModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Mvc.ModelBinding;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Apollo.Integrator.Models.EntityGroup
{
    public record EntityGroupModel : BaseNopEntityModel
    {
        public EntityGroupModel()
        {
            AvailableEntity = new List<SelectListItem>();
            AvailableStores = new List<SelectListItem>();
            AvailableWarehouses = new List<SelectListItem>();
            AvailableVendors = new List<SelectListItem>();
            KeyGroupList = new List<SelectListItem>();
            KeyList = new List<SelectListItem>();
        }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Store")]
        public int StoreId { get; set; }
        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Store")]
        public string StoreName { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Warehouse")]
        public int WarehouseId { get; set; }
        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Warehouse")]
        public string WarehouseName { get; set; }

        [NopResourceDisplayName("Admin.Catalog.Products.Fields.Vendor")]
        public int VendorId { get; set; }
        [NopResourceDisplayName("Admin.Catalog.Products.Fields.Vendor")]
        public string VendorName { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.KeyGroup")]
        public string KeyGroup { get; set; }
        public int KeyGroupId { get; set; }
        public IList<SelectListItem> KeyGroupList { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Entity")]
        public int EntityId { get; set; }
        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Entity")]
        public string EntityName { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Key")]
        public string Key { get; set; }
        public int KeyId { get; set; }
        public IList<SelectListItem> KeyList { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Value")]
        public string Value { get; set; }
        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Value")]
        public string ValueName { get; set; }

        public IList<SelectListItem> AvailableEntity { get; set; }
        public IList<SelectListItem> AvailableStores { get; set; }
        public IList<SelectListItem> AvailableWarehouses { get; set; }
        public IList<SelectListItem> AvailableVendors { get; set; }
    }
}

Models/EntityGroup/EntityGroupSearchModel.cs
using Nop.Web.Framework.Mvc.ModelBinding;
using Nop.Web.Framework.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Nop.Plugin.Apollo.Integrator.Models.EntityGroup
{
    public record EntityGroupSearchModel : BaseSearchModel
    {
        public EntityGroupSearchModel()
        {
            AvailableEntity = new List<SelectListItem>();
            AvailableStores = new List<SelectListItem>();
            AvailableWarehouses = new List<SelectListItem>();
            AvailableVendors = new List<SelectListItem>();
            KeyGroupList = new List<SelectListItem>();
            KeyList = new List<SelectListItem>();
        }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.LimitMethodsToCreated")]
        public bool LimitMethodsToCreated { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.ReturnValidOptionsIfThereAreAny")]
        public bool ReturnValidOptionsIfThereAreAny { get; set; }

        public bool ShippingByWeightByTotalEnabled { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Store")]
        public int SearchStoreId { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Warehouse")]
        public int SearchWarehouseId { get; set; }

        [NopResourceDisplayName("Admin.Catalog.Products.Fields.Vendor")]
        public int SearchVendorId { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.KeyGroup")]
        public int SearchKeyGroupId { get; set; }
        public string SearchKeyGroup { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Entity")]
        public int SearchEntityId { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Key")]
        public int SearchKeyId { get; set; }
        public string SearchKey { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Value")]
        public string SearchValue { get; set; }
        
        public IList<SelectListItem> AvailableEntity { get; set; }
        public IList<SelectListItem> AvailableStores { get; set; }
        public IList<SelectListItem> AvailableWarehouses { get; set; }
        public IList<SelectListItem> AvailableVendors { get; set; }
        public IList<SelectListItem> KeyGroupList { get; set; }
        public IList<SelectListItem> KeyList { get; set; }
    }
}

Models/EntityGroup/VendorScopeConfigurationModel.cs
using System.Collections.Generic;
using Nop.Web.Areas.Admin.Models.Vendors;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Apollo.Integrator.Models.EntityGroup
{
    /// <summary>
    /// Represents a store scope configuration model
    /// </summary>
    public partial record VendorScopeConfigurationModel : BaseNopModel
    {
        #region Ctor

        public VendorScopeConfigurationModel()
        {
            Vendors = new List<VendorModel>();
            VendorGroupMembers = new List<VendorModel>();
        }

        #endregion

        #region Properties

        public int VendorId { get; set; }

        public IList<VendorModel> Vendors { get; set; }

        public int GroupVendorId { get; set; }

        public IList<VendorModel> VendorGroupMembers { get; set; }

        public bool DisplayControl { get; set; }

        public bool DisplayControlVendorGroups { get; set; }

        #endregion
    }
}

Controllers/EntityGroupController.cs
using System;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Domain.Directory;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Shipping;
using Nop.Services.Stores;
using Nop.Services.Vendors;
using Nop.Web.Framework;
using Nop.Web.Framework.Extensions;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Models.Extensions;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

using Nop.Plugin.Shipping.Manager.Services;
using Nop.Plugin.Shipping.Manager.Settings;

using Nop.Plugin.Apollo.Integrator;
using Nop.Plugin.Apollo.Integrator.Domain;
using Nop.Plugin.Apollo.Integrator.Services;
using Nop.Plugin.Apollo.Integrator.Models.EntityGroup;

namespace Nop.Plugin.Shipping.Manager.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.ADMIN)]
    public class EntityGroupController : BasePluginController
    {

        #region Fields

        protected readonly CurrencySettings _currencySettings;
        protected readonly ShippingManagerSettings _shippingManagerSettings;
        protected readonly ICurrencyService _currencyService;
        protected readonly ILocalizationService _localizationService;
        protected readonly IMeasureService _measureService;
        protected readonly IPermissionService _permissionService;
        protected readonly ISettingService _settingService;
        protected readonly IStateProvinceService _stateProvinceService;
        protected readonly IStoreService _storeService;
        protected readonly MeasureSettings _measureSettings;
        protected readonly IShippingService _shippingService;
        protected readonly IShippingManagerService _shippingManagerService;
        protected readonly IVendorService _vendorService;
        protected readonly INotificationService _notificationService;
        protected readonly IStoreContext _storeContext;
        protected readonly IWorkContext _workContext;
        protected readonly IEntityGroupService _entityGroupService;
        protected readonly IShippingManagerInstallService _shippingManagerInstallService;
        protected readonly ILogger _logger;
        protected readonly IGenericAttributeService _genericAttributeService;


        SystemHelper _systemHelper = new SystemHelper();

        #endregion

        #region Ctor

        public EntityGroupController(CurrencySettings currencySettings,
            ShippingManagerSettings shippingManagerSettings,
            ICurrencyService currencyService,
            ILocalizationService localizationService,
            IMeasureService measureService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStateProvinceService stateProvinceService,
            IStoreService storeService,
            MeasureSettings measureSettings,
            IShippingService shippingService,
            IShippingManagerService shippingManagerService,
            IVendorService vendorService,
            INotificationService notificationService,
            IStoreContext storeContext,
            IWorkContext workContext,
            IEntityGroupService entityGroupService,
            IShippingManagerInstallService shippingManagerInstallService,
            ILogger logger,
            IGenericAttributeService genericAttributeService)
        {
            _currencySettings = currencySettings;
            _shippingManagerSettings = shippingManagerSettings;
            _currencyService = currencyService;
            _localizationService = localizationService;
            _measureService = measureService;
            _permissionService = permissionService;
            _settingService = settingService;
            _stateProvinceService = stateProvinceService;
            _storeService = storeService;
            _measureSettings = measureSettings;
            _shippingService = shippingService;
            _shippingManagerService = shippingManagerService;
            _vendorService = vendorService;
            _notificationService = notificationService;
            _storeContext = storeContext;
            _workContext = workContext;
            _entityGroupService = entityGroupService;
            _shippingManagerInstallService = shippingManagerInstallService;
            _logger = logger;
            _genericAttributeService = genericAttributeService;
        }

        #endregion

        #region Utility

        public virtual async Task<IActionResult> ChangeVendorScopeConfiguration(int vendorid, string returnUrl = "")
        {
            var customer = await _workContext.GetCurrentCustomerAsync();

            var vendor = await _vendorService.GetVendorByIdAsync(vendorid);
            if (vendor != null || vendorid == 0)
            {
                await _genericAttributeService.SaveAttributeAsync(customer, ApolloIntegratorDefaults.AdminAreaVendorScopeConfigurationAttribute, vendorid);
                await _genericAttributeService.SaveAttributeAsync(customer, ApolloIntegratorDefaults.AdminAreaGroupVendorScopeConfigurationAttribute, 0);
            }

            return Redirect(returnUrl);
        }

        public virtual async Task<IActionResult> ChangeGroupVendorScopeConfiguration(int vendorid, string returnUrl = "")
        {
            var customer = await _workContext.GetCurrentCustomerAsync();

            var vendor = await _vendorService.GetVendorByIdAsync(vendorid);
            if (vendor != null || vendorid == 0)
            {
                await _genericAttributeService.SaveAttributeAsync(customer, ApolloIntegratorDefaults.AdminAreaGroupVendorScopeConfigurationAttribute, vendorid);
            }

            return Redirect(returnUrl);
        }

        #endregion

        #region Entity Group Methods

        public async Task<IActionResult> EntityGroup()
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Configure))
                return AccessDeniedView();

            var model = new EntityGroupSearchModel
            {

            };

            //stores
            model.AvailableStores.Add(new SelectListItem { Text = "*", Value = "0" });
            foreach (var store in await _storeService.GetAllStoresAsync())
                model.AvailableStores.Add(new SelectListItem { Text = store.Name, Value = store.Id.ToString() });

            //warehouses
            model.AvailableWarehouses.Add(new SelectListItem { Text = "*", Value = "0" });
            foreach (var warehouses in await _shippingService.GetAllWarehousesAsync())
                model.AvailableWarehouses.Add(new SelectListItem { Text = warehouses.Name, Value = warehouses.Id.ToString() });

            //vendors
            model.AvailableVendors.Add(new SelectListItem { Text = "*", Value = "0" });
            foreach (var vendors in await _vendorService.GetAllVendorsAsync())
                model.AvailableVendors.Add(new SelectListItem { Text = vendors.Name, Value = vendors.Id.ToString() });

            //prepare available entity
            model.AvailableEntity.Add(new SelectListItem { Text = "*", Value = "0" });
            var entities = _entityGroupService.GetAllEntityGroups(null, 0, null, null);
            foreach (var e in entities)
                model.AvailableEntity.Add(new SelectListItem { Text = e.KeyGroup + " " + e.EntityId.ToString(), Value = e.Id.ToString() });

            //KeyGroup
            int number = 0;
            model.KeyGroupList.Add(new SelectListItem { Text = "*", Value = number.ToString() });
            foreach (var entity in Enum.GetNames(typeof(EntityGroupTypes.KeyGroup)))
            {
                number++;
                model.KeyGroupList.Add(new SelectListItem { Text = entity, Value = number.ToString() });
            }

            //Key
            number = 0;
            model.KeyList.Add(new SelectListItem { Text = "*", Value = number.ToString() });
            foreach (var entity in Enum.GetNames(typeof(EntityGroupTypes.Key)))
            {
                number++;
                model.KeyList.Add(new SelectListItem { Text = entity, Value = number.ToString() });
            }

            model.SetGridPageSize();

            return View("~/Plugins/SSI.Shipping.Manager/Views/EntityGroup/EntityGroup.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> EntityGroup(EntityGroupModel model)
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Configure))
                return Content("Access denied");

            return Json(new { Result = true });
        }

        [HttpPost]
        public async Task<IActionResult> SaveMode(bool value)
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Manage))
                return Content("Access denied");

            return Json(new { Result = true });
        }

        #endregion

        #region Entity Groups

        [HttpPost]
        public async Task<IActionResult> EntityGroupList(EntityGroupSearchModel searchModel, EntityGroupSearchModel filter)
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Configure))
                return AccessDeniedView();

            filter.SearchKeyGroup = Enum.GetName(typeof(EntityGroupTypes.KeyGroup), filter.SearchKeyGroupId - 1);
            filter.SearchKey = Enum.GetName(typeof(EntityGroupTypes.Key), filter.SearchKeyId - 1);
            if (searchModel.AvailableStores.SelectionIsNotPossible())
                filter.SearchStoreId = await _entityGroupService.GetActiveStoreScopeConfiguration();

            var records = _entityGroupService.GetAllEntityGroups(
                pageIndex: searchModel.Page - 1,

Views/EntityGroup/AddEntityGroupPopup.cshtml
@model EntityGroupModel

@{
    Layout = "_AdminPopupLayout";
}

<form asp-controller="EntityGroup" asp-action="AddEntityGroupPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Common.AddNew")
        </h1>
        <div class="float-right">
            <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/EntityGroup/_CreateOrUpdateEntityGroup.cshtml", Model)
        </div>
    </div>
</form>

Views/EntityGroup/EditEntityGroupPopup.cshtml
@model EntityGroupModel

@{
    Layout = "_AdminPopupLayout";
}

<form asp-controller="EntityGroup" asp-action="EditEntityGroupPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Common.Edit")
        </h1>
        <div class="float-right">
            <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/EntityGroup/_CreateOrUpdateEntityGroup.cshtml", Model)
        </div>
    </div>
</form>

Views/EntityGroup/EntityGroup.cshtml
@model EntityGroupSearchModel

@{
    Layout = "_AdminLayout";

    //page title
    ViewBag.Title = T("Plugins.Shipping.Manager.EntityGroup").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Nop.Plugins.Shipping.Manager.EntityGroup");
}

<div class="content-header clearfix">
    <h1 class="float-left">
        @T("Plugins.Shipping.Manager.EntityGroup")
    </h1>
</div>

<div class="content">
    <div class="form-horizontal">
        @await Component.InvokeAsync("VendorScopeConfiguration")
        <div class="cards-group">
            <div class="card-body">
                <div class="row">
                    @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/EntityGroup/_EntityGroupRelationships.cshtml")
                </div>
            </div>
        </div>
    </div>
</div>
<nop-alert asp-alert-id="saveModeAlert" asp-alert-message="@T("Admin.Common.Alert.Save.Error")" />

Views/EntityGroup/_EntityGroupRelationships.cshtml
@model EntityGroupSearchModel

@using Nop.Plugin.Shipping.Manager.Models

@{
    var stores = await storeService.GetAllStoresAsync();

    const string hideSearchBlockAttributeName = "EntityGroupsPage.HideSearchBlock";
    var hideSearchBlock = await genericAttributeService.GetAttributeAsync<bool>(await workContext.GetCurrentCustomerAsync(), hideSearchBlockAttributeName);
}

<form asp-controller="EntityGroup" asp-action="EntityGroup" method="post" id="entity-group-form">
    <div class="cards-group advanced-setting">
        <div class="form-horizontal">
            <div class="card card-default card-search">
                <div class="card-body">
                    <div class="row search-row @(!hideSearchBlock ? "opened" : "")" data-hideAttribute="@hideSearchBlockAttributeName">
                        <div class="search-text">@T("Admin.Common.Search")</div>
                        <div class="icon-search"><i class="fa fa-search" aria-hidden="true"></i></div>
                        <div class="icon-collapse"><i class="fa fa-angle-down" aria-hidden="true"></i></div>
                    </div>
                    <div class="search-body @(hideSearchBlock ? "closed" : "")">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group row" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                    <div class="col-md-4">
                                        <nop-label asp-for="SearchStoreId" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-select asp-for="SearchStoreId" asp-items="Model.AvailableStores" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="SearchVendorId" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-select asp-for="SearchVendorId" asp-items="Model.AvailableVendors" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="SearchWarehouseId" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-select asp-for="SearchWarehouseId" asp-items="Model.AvailableWarehouses" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group row">
                                    <div class="col-sm-4">
                                        <nop-label asp-for="SearchKeyGroupId" />
                                    </div>
                                    <div class="col-sm-6">
                                        <nop-select asp-for="SearchKeyGroupId" asp-items="Model.KeyGroupList" />
                                        <span asp-validation-for="SearchKeyGroupId"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-4">
                                        <nop-label asp-for="SearchKeyId" />
                                    </div>
                                    <div class="col-sm-6">
                                        <nop-select asp-for="SearchKeyId" asp-items="Model.KeyList" />
                                        <span asp-validation-for="SearchKeyId"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="SearchEntityId" />
                                    </div>
                                    <div class="col-md-6">
                                        <nop-select asp-for="SearchEntityId" asp-items="Model.AvailableEntity" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="text-center col-12">
                                <button type="button" id="search-entity-group-records" class="btn btn-primary btn-search">
                                    <i class="fas fa-search"></i>
                                    @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card card-default">
                <div class="card-body">
                    <p>
                        <b>@T("Plugins.Shipping.Manager.EntityGroup.Instruction")</b>
                        @T("Plugins.Shipping.Manager.EntityGroup.Instruction.Hint   ")
                    </p>
                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                    Name = "entity-group-grid",
                    UrlRead = new DataUrl("EntityGroupList", "EntityGroup", null),
                    UrlDelete = new DataUrl("DeleteEntityGroup", "EntityGroup", null),
                    SearchButtonId = "search-entity-group-records",
                    Length = Model.PageSize,
                    LengthMenu = Model.AvailablePageSizes,
                    Filters = new List<FilterParameter>
                    {
                        new FilterParameter(nameof(Model.SearchStoreId)),
                        new FilterParameter(nameof(Model.SearchWarehouseId)),
                        new FilterParameter(nameof(Model.SearchVendorId)),
                        new FilterParameter(nameof(Model.SearchEntityId)),
                        new FilterParameter(nameof(Model.SearchKeyGroupId)),
                        new FilterParameter(nameof(Model.SearchKeyId)),
                    },
                    ColumnCollection = new List<ColumnProperty>
                    {
                        new ColumnProperty(nameof(EntityGroupModel.KeyGroup))
                        {
                            Title = T("Plugins.Shipping.Manager.Fields.KeyGroup").Text,
                            Width = "200"
                        },
                        new ColumnProperty(nameof(EntityGroupModel.EntityName))
                        {
                            Title = T("Plugins.Shipping.Manager.Fields.Entity").Text,
                            Width = "200"
                        },
                        new ColumnProperty(nameof(EntityGroupModel.Key))
                        {
                            Title = T("Plugins.Shipping.Manager.Fields.Key").Text,
                            Width = "200"
                        },
                        new ColumnProperty(nameof(EntityGroupModel.Value))
                        {
                            Title = T("Plugins.Shipping.Manager.Fields.Value").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll,
                            Width = "100",
                        },
                        new ColumnProperty(nameof(EntityGroupModel.StoreName))
                        {
                            Title = T("Plugins.Shipping.Manager.Fields.Store").Text,
                            Width = "200",
                            Visible = stores.Count > 1
                        },
                        new ColumnProperty(nameof(EntityGroupModel.VendorName))
                        {
                            Title = T("Admin.Catalog.Products.Fields.Vendor").Text,
                            Width = "200"
                        },
                        new ColumnProperty(nameof(EntityGroupModel.WarehouseName))
                        {
                            Title = T("Plugins.Shipping.Manager.Fields.Warehouse").Text,
                            Width = "200"
                        },
                        new ColumnProperty(nameof(EntityGroupModel.Id))
                        {
                            Title = T("Admin.Common.Edit").Text,
                            ClassName = NopColumnClassDefaults.Button,
                            Width = "100",
                            Render = new RenderCustom("renderColumnEdit")
                        },
                        new ColumnProperty(nameof(EntityGroupModel.Id))
                        {
                            Title = T("Admin.Common.Delete").Text,
                            ClassName = NopColumnClassDefaults.Button,
                            Render = new RenderButtonRemove(T("Admin.Common.Delete").Text),
                            Width = "100"
                        }
                    }
                })
                </div>
                <div class="card-footer">
                    <button type="submit" id="btnAddNewRecord" class="btn btn-primary"
                            onclick="javascript:OpenWindow('@(Url.Action("AddEntityGroupPopup", "EntityGroup", new {btnId = "btnRefresh", formId = "entity-group-form"}))', 600, 600, true);return false;">
                        @T("Plugins.Shipping.Manager.AddRecord")
                    </button>
                </div>
            </div>
        </div>
    </div>
    <script>
        function renderColumnEdit(data, type, row, meta) {
            return '<button onclick=\"javascript:OpenWindow(\'@Url.Action("EditEntityGroupPopup", "EntityGroup")?id='
                + data + '&btnId=btnRefresh&formId=entity-group-form\', 600, 600, true); return false;\" class="btn btn-default"><i class="fa fa-pencil"></i>@T("Admin.Common.Edit")</button>';
        }
        $(document)
            .ready(function () {
                $('#btnRefresh')
                    .click(function () {
                        //refresh grid
                        updateTable('#entity-group-grid');
                        //return false to don't reload a page
                        return false;
                    });
            });
    </script>
</form>