Models/Order/OrderItemListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Order
{
    /// <summary>
    /// Represents a order item list model
    /// </summary>
    public partial record OrderItemListModel : BasePagedListModel<OrderItemModel>
    {
    }
}

Models/Order/OrderItemModel.cs
using System.Collections.Generic;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Shipping.Manager.Models.Order
{
    /// <summary>
    /// Represents a shipment item model
    /// </summary>
    public partial record OrderItemModel : BaseNopEntityModel
    {
        #region Ctor

        public OrderItemModel()
        {
            ProductName = string.Empty;
            AttributeInfo = string.Empty;
            RentalInfo = string.Empty;
        }

        #endregion

        #region Properties

        public int OrderItemId { get; set; }

        public int ProductId { get; set; }

        [NopResourceDisplayName("Admin.Orders.Shipments.Products.ProductName")]
        public string ProductName { get; set; }

        public string AttributeInfo { get; set; }

        public string RentalInfo { get; set; }

        public int Quantity { get; set; }

        public string Price { get; set; }

        public string Warehouse { get; set; }

        #endregion

        #region Nested Classes

        public record WarehouseInfo : BaseNopModel
        {
            public int WarehouseId { get; set; }
            public string WarehouseName { get; set; }
            public int StockQuantity { get; set; }
            public int ReservedQuantity { get; set; }
            public int PlannedQuantity { get; set; }
            public int ToShipQuatity { get; set; }
            public bool IsPreSelected { get; set; }
        }

        #endregion
    }
}

Models/Order/OrderItemSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Order
{
    /// <summary>
    /// Represents a shipment item search model
    /// </summary>
    public partial record OrderItemSearchModel : BaseSearchModel
    {
        #region Properties

        public int OrderId { get; set; }

        #endregion
    }
}

Models/Order/OrderSalesModels.cs
using System;
using System.Collections.Generic;
using Nop.Web.Framework.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;

namespace Nop.Plugin.Shipping.Manager.Models.Order
{

    public record OrderSalesModel : BaseNopEntityModel
    {
        public OrderSalesModel()
        {
            AvailableGroupProducts = new List<SelectListItem>();
            AvailableAssociatedProducts = new List<SelectListItem>();
            AvailablePaymentMethods = new List<SelectListItem>();
            PaymentDate = string.Empty;
            PaymentMethod = string.Empty;
            Name = string.Empty;
            ParentProduct = string.Empty;
            AttributeDescription = string.Empty;
            RentalDescription = string.Empty;
            Customer = string.Empty;
            PaymentStatus = string.Empty;
            Price = string.Empty;
            TotalPrice = string.Empty;
            PaymentMethodSystemName = string.Empty;
            CustomerEmail = string.Empty;
            CustomerFullName = string.Empty;
            ShippingMethodSystemName = string.Empty;
            DisplayUrl = string.Empty;
            ShipmentUrl = string.Empty;
            Status = string.Empty;
            AvailableWarehouse = new List<SelectListItem>();
        }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.FromDate")]
        public DateTime? FromDate { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.ToDate")]
        public DateTime? ToDate { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.PaymentDate")]
        public string PaymentDate { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.IsPay")]
        public bool Ispay { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.OrderbyName")]
        public bool OrderbyName { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.PaymentMethod")]
        public string PaymentMethod { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.GroupProductId")]
        public int GroupProductId { get; set; }
        public IList<SelectListItem> AvailableGroupProducts { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.AssociatedProductId")]
        public int AssociatedProductId { get; set; }

        public IList<SelectListItem> AvailableAssociatedProducts { get; set; }

        public List<SelectListItem> AvailablePaymentMethods { get; set; }

        public int OrderItemId { get; set; }

        public int ProductId { get; set; }

        public string Name { get; set; }

        public string ParentProduct { get; set; }

        public string AttributeDescription { get; set; }

        public string RentalDescription { get; set; }

        public string Customer { get; set; }

        public int Quantity { get; set; }

        public int OrderId { get; set; }

        public string PaymentStatus { get; set; }

        public string Price { get; set; }

        public string TotalPrice { get; set; }

        public string PaymentMethodSystemName { get; set; }

        public string CustomerEmail { get; set; }

        public string CustomerFullName { get; set; }

        public string ShippingMethodSystemName { get; set; }

        public string DisplayUrl { get; set; }

        public string ShipmentUrl { get; set; }

        public string Status { get; set; }

        public List<SelectListItem> AvailableWarehouse { get; set; }

        public DateTime? OrderCreatedDate { get; set; }

    }

    public partial record OrderSalesListModel : BasePagedListModel<OrderSalesModel>
    {
    }

    public partial record OrderSalesSearchModel : BaseSearchModel
    {
        public OrderSalesSearchModel()
        {
            AvailablePaymentMethods = new List<SelectListItem>();
            PaymentMethod = string.Empty;
            SearchProductName = string.Empty;
        }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.SearchProductName")]
        public string SearchProductName { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.FromDate")]
        [UIHint("DateNullable")]
        public DateTime? FromDate { get; set; }

        public DateTime? FDate { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.ToDate")]
        [UIHint("DateNullable")]
        public DateTime? ToDate { get; set; }

        public DateTime? TDate { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.IsPay")]
        public bool Ispay { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.OrderbyName")]
        public bool OrderbyName { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.Sales.Fields.PaymentMethod")]
        public string PaymentMethod { get; set; }

        public List<SelectListItem> AvailablePaymentMethods { get; set; }
    }

}

Models/Order/ShipmentEventModel.cs
using System;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Order
{
    /// <summary>
    /// Represents a shipment event model
    /// </summary>
    public partial record ShipmentStatusEventModel : BaseNopModel
    {
        #region Properties

        public string EventName { get; set; }

        public string Location { get; set; }

        public string Country { get; set; }

        public DateTime? Date { get; set; }

        #endregion
    }
}

Controllers/OrderOperationsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Common;
using Nop.Core.Domain.Directory;
using Nop.Core.Domain.Logging;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Shipping;
using Nop.Plugin.Apollo.Integrator;
using Nop.Plugin.Apollo.Integrator.Services;
using Nop.Plugin.Shipping.Manager.Domain;
using Nop.Plugin.Shipping.Manager.Models.Order;
using Nop.Plugin.Shipping.Manager.Services;
using Nop.Plugin.Shipping.Manager.Settings;
using Nop.Services.Attributes;
using Nop.Services.Catalog;
using Nop.Services.Common;
using Nop.Services.Directory;
using Nop.Services.ExportImport;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Payments;
using Nop.Services.Security;
using Nop.Services.Shipping;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

using Nop.Plugin.Shipping.Manager.Factories;

namespace Nop.Plugin.Shipping.Manager.Controllers;

public partial class OrderOperationsController : BaseAdminController
{

    #region Fields

    protected readonly IAttributeParser<AddressAttribute, AddressAttributeValue> _addressAttributeParser;
    protected readonly IAddressService _addressService;
    protected readonly ICountryService _countryService;
    protected readonly ICustomerActivityService _customerActivityService;
    protected readonly IDateTimeHelper _dateTimeHelper;
    protected readonly IDownloadService _downloadService;
    protected readonly IEncryptionService _encryptionService;
    protected readonly IExportManager _exportManager;
    protected readonly IGiftCardService _giftCardService;
    protected readonly ILocalizationService _localizationService;
    protected readonly INotificationService _notificationService;
    protected readonly IOrderOperationsModelFactory _orderOperationsModelFactory;
    protected readonly IOrderProcessingService _orderProcessingService;
    protected readonly IOrderService _orderService;
    protected readonly IPaymentService _paymentService;
    protected readonly IPdfService _pdfService;
    protected readonly IPermissionService _permissionService;
    protected readonly IPriceCalculationService _priceCalculationService;
    protected readonly IProductAttributeFormatter _productAttributeFormatter;
    protected readonly IProductAttributeParser _productAttributeParser;
    protected readonly IProductAttributeService _productAttributeService;
    protected readonly IProductService _productService;
    protected readonly IShipmentService _shipmentService;
    protected readonly IShippingService _shippingService;
    protected readonly IShoppingCartService _shoppingCartService;
    protected readonly IWorkContext _workContext;
    protected readonly IWorkflowMessageService _workflowMessageService;
    protected readonly OrderSettings _orderSettings;
    protected readonly IShippingManagerService _shippingManagerService;
    protected readonly IEntityGroupService _entityGroupService;
    protected readonly ShippingManagerSettings _shippingManagerSettings;
    protected readonly ILogger _logger;
    protected readonly ISendcloudService _sendcloudService;
    protected readonly ICanadaPostService _canadaPostService;
    protected readonly IOrderItemPdfService _orderItemPdfService;
    protected readonly IFastwayService _fastwayService;
    protected readonly IPackagingOptionService _packagingOptionService;
    protected readonly IShipmentDetailsService _shipmentDetailsService;
    protected readonly ICarrierService _carrierService;

    #endregion

    #region Ctor

    public OrderOperationsController(IAttributeParser<AddressAttribute, AddressAttributeValue> addressAttributeParser,
        IAddressService addressService,
        ICountryService countryService,
        ICustomerActivityService customerActivityService,
        IDateTimeHelper dateTimeHelper,
        IDownloadService downloadService,
        IEncryptionService encryptionService,
        IExportManager exportManager,
        IGiftCardService giftCardService,
        ILocalizationService localizationService,
        INotificationService notificationService,
        IOrderOperationsModelFactory orderOperationsModelFactory,
        IOrderProcessingService orderProcessingService,
        IOrderService orderService,
        IPaymentService paymentService,
        IPdfService pdfService,
        IPermissionService permissionService,
        IPriceCalculationService priceCalculationService,
        IProductAttributeFormatter productAttributeFormatter,
        IProductAttributeParser productAttributeParser,
        IProductAttributeService productAttributeService,
        IProductService productService,
        IShipmentService shipmentService,
        IShippingService shippingService,
        IShoppingCartService shoppingCartService,
        IWorkContext workContext,
        IWorkflowMessageService workflowMessageService,
        OrderSettings orderSettings,
        IShippingManagerService shippingManagerService,
        IEntityGroupService entityGroupService,
        ShippingManagerSettings shippingManagerSettings,
        ILogger logger,
        ISendcloudService sendcloudService,
        ICanadaPostService canadaPostService,
        IOrderItemPdfService orderItemPdfService,
        IFastwayService fastwayService,
        IPackagingOptionService packagingOptionService,
        IShipmentDetailsService shipmentDetailsService,
        ICarrierService carrierService)
    {
        _addressAttributeParser = addressAttributeParser;
        _addressService = addressService;
        _countryService = countryService;
        _customerActivityService = customerActivityService;
        _dateTimeHelper = dateTimeHelper;
        _downloadService = downloadService;
        _encryptionService = encryptionService;
        _exportManager = exportManager;
        _giftCardService = giftCardService;
        _localizationService = localizationService;
        _notificationService = notificationService;
        _orderOperationsModelFactory = orderOperationsModelFactory;
        _orderProcessingService = orderProcessingService;
        _orderService = orderService;
        _paymentService = paymentService;
        _pdfService = pdfService;
        _permissionService = permissionService;
        _priceCalculationService = priceCalculationService;
        _productAttributeFormatter = productAttributeFormatter;
        _productAttributeParser = productAttributeParser;
        _productAttributeService = productAttributeService;
        _productService = productService;
        _shipmentService = shipmentService;
        _shippingService = shippingService;
        _shoppingCartService = shoppingCartService;
        _workContext = workContext;
        _workflowMessageService = workflowMessageService;
        _orderSettings = orderSettings;
        _shippingManagerService = shippingManagerService;
        _entityGroupService = entityGroupService;
        _shippingManagerSettings = shippingManagerSettings;
        _logger = logger;
        _sendcloudService = sendcloudService;
        _canadaPostService = canadaPostService;
        _orderItemPdfService = orderItemPdfService;
        _fastwayService = fastwayService;
        _packagingOptionService = packagingOptionService;
        _shipmentDetailsService = shipmentDetailsService;
        _carrierService = carrierService;
    }

    #endregion

    #region Utilities

    protected virtual async ValueTask<bool> HasAccessToOrderAsync(Order order)
    {
        return order != null && await HasAccessToOrderAsync(order.Id);
    }

    protected virtual async Task<bool> HasAccessToOrderAsync(int orderId)
    {
        if (orderId == 0)
            return false;

        if (await _workContext.GetCurrentVendorAsync() == null)
            //not a vendor; has access
            return true;

        var vendorId = (await _workContext.GetCurrentVendorAsync()).Id;
        var hasVendorProducts = (await _orderService.GetOrderItemsAsync(orderId, vendorId: vendorId)).Any();

        return hasVendorProducts;
    }

    protected virtual async Task<bool> HasAccessToOrderItemAsync(OrderItem orderItem)
    {
        if (orderItem == null)
            throw new ArgumentNullException(nameof(orderItem));

        var vendor = await _workContext.GetCurrentVendorAsync();
        if (vendor == null)
            //not a vendor; has access
            return true;

        var vendorId = vendor.Id;
        var product = await _productService.GetProductByIdAsync(orderItem.ProductId);

        return product.VendorId == vendorId;
    }

    protected virtual async ValueTask<bool> HasAccessToProductAsync(OrderItem orderItem)
    {
        if (orderItem == null || orderItem.ProductId == 0)
            return false;

        if (await _workContext.GetCurrentVendorAsync() == null)
            //not a vendor; has access
            return true;

        var vendorId = (await _workContext.GetCurrentVendorAsync()).Id;

        return (await _productService.GetProductByIdAsync(orderItem.ProductId))?.VendorId == vendorId;
    }

    protected virtual async ValueTask<bool> HasAccessToShipmentAsync(Shipment shipment)
    {
        if (shipment == null)
            throw new ArgumentNullException(nameof(shipment));

        if (await _workContext.GetCurrentVendorAsync() == null)
            //not a vendor; has access
            return true;

        return await HasAccessToOrderAsync(shipment.OrderId);
    }

    /// <returns>A task that represents the asynchronous operation</returns>
    protected virtual async Task LogEditOrderAsync(int orderId)
    {

Views/Order/AddShipment.cshtml
@model Nop.Plugin.Shipping.Manager.Models.Order.ShipmentModel

@using System.Text

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminPopupLayout.cshtml";

    //page title
    ViewBag.Title = string.Format(T("Admin.Orders.Shipments.AddNew.Title").Text, Model.CustomOrderNumber);
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Nop.Plugins.Shipping.Manager.Shipments");

    var itemsFromMultipleWarehouses = Model.Items
        .Where(x => x.AllowToChooseWarehouse && x.AvailableWarehouses.Count > 0)
        .ToList();
}

<form asp-controller="OrderOperations" asp-action="AddShipment" asp-route-orderId="@Model.OrderId" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @string.Format(T("Admin.Orders.Shipments.AddNew.Title").Text, Model.CustomOrderNumber)
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="Edit" asp-route-id="@Model.OrderId">@T("Admin.Orders.Shipments.BackToOrder")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" id="shipment-save" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" id="shipment-save-continue" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <nop-action-confirmation asp-button-id="shipment-save" asp-additional-confirm="Admin.Orders.Shipments.Products.Warehouse.QuantityNotEnough" />
            <nop-action-confirmation asp-button-id="shipment-save-continue" asp-additional-confirm="Admin.Orders.Shipments.Products.Warehouse.QuantityNotEnough"/>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.OrderShipmentAddButtons })
        </div>
    </div>
    <div asp-validation-summary="All"></div>

    <div class="content">
        <div class="form-horizontal">
            <div class="cards-group">
                <div class="card card-default">
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="TrackingNumber" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="TrackingNumber" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="AdminComment" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="AdminComment" />
                            </div>
                        </div>
                    </div>
                    <script>
                        $(document).ready(function () {
                            $("#shipment-save").bind("focus", function () {
                                if (validateWarehouseAvailability("save")) {
                                    $("#shipment-save-action-confirmation").remove();
                                    $(this).attr("name", "save").attr("type", "submit");
                                }
                            }).bind("click", function () {
                                return validateWarehouseAvailability("save");
                            });;

                            $("#shipment-save-continue").bind("focus", function () {
                                if (validateWarehouseAvailability("continue")) {
                                    $("#shipment-save-continue-action-confirmation").remove();
                                    $(this).attr("name", "save-continue").attr("type", "submit");
                                }
                            }).bind("click", function () {
                                return validateWarehouseAvailability("continue");
                            });;
                        });

                        function validateWarehouseAvailability(action) {
                            @{
                                var sb = new StringBuilder();
                                var count = itemsFromMultipleWarehouses.Count;
                                if (count == 0)
                                {
                                    sb.Append("true");
                                }
                                else
                                {
                                    for (var i = 0; i <= count - 1; i++)
                                    {
                                        var item = itemsFromMultipleWarehouses[i];
                                        sb.AppendFormat("validateAvailableQuantity('{0}')", item.OrderItemId);
                                        if (i != count - 1)
                                        {
                                            sb.Append(" && ");
                                        }
                                    }
                                }
                            }
                            var valid = @(Html.Raw(sb.ToString()));
                            if (!valid) {
                                if (action === "save") {
                                    $('#shipment-save-action-confirmation').modal('toggle');
                                }
                                if (action === "continue") {
                                    $('#shipment-save-continue-action-confirmation').modal('toggle');
                                }
                                return false;
                            }
                            return true;
                        }

                        function validateAvailableQuantity(orderItemId) {
                            var enteredValue = parseInt($('#qtyToAdd' + orderItemId).val(), 10);
                            if (enteredValue <= 0)
                                return true;
                            var reservedValue = parseInt($('#warehouse_' + orderItemId).find(':selected').data('reserved-qty'), 10);
                            var plannedValue = parseInt($('#warehouse_' + orderItemId).find(':selected').data('planned-qty'), 10);
                            var availableToAdd = reservedValue - plannedValue;
                            return enteredValue <= availableToAdd;
                        }
                    </script>
                </div>

                <div class="card card-default">
                    <div class="card-header">
                        @T("Admin.Orders.Shipments.Products")
                    </div>
                    <div class="card-body">
                        <table class="table table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>
                                        @T("Admin.Orders.Shipments.Products.ProductName")
                                    </th>
                                    <th>
                                        @T("Admin.Orders.Shipments.Products.SKU")
                                    </th>
                                    <th>
                                        @T("Admin.Orders.Shipments.Products.Warehouse")
                                    </th>
                                    <th>
                                        @T("Admin.Orders.Shipments.Products.ItemWeight")
                                    </th>
                                    <th>
                                        @T("Admin.Orders.Shipments.Products.ItemDimensions")
                                    </th>
                                    <th>
                                        @T("Admin.Orders.Shipments.Products.QtyOrdered")
                                    </th>
                                    <th>
                                        @T("Admin.Orders.Shipments.Products.QtyShipped")
                                    </th>
                                    <th>
                                        @T("Admin.Orders.Shipments.Products.QtyToShip")
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td style="width: 25%;" class="text-left">
                                            <em><a asp-controller="Product" asp-action="Edit" asp-route-id="@item.ProductId">@item.ProductName</a></em>
                                            @if (!string.IsNullOrEmpty(item.AttributeInfo))
                                            {
                                                <p>
                                                    @Html.Raw(item.AttributeInfo)
                                                </p>
                                            }
                                            @if (item.ShipSeparately)
                                            {
                                                <p>
                                                    <strong>@T("Admin.Orders.Shipments.Products.ShipSeparately.Warning")</strong>
                                                    @T("Admin.Orders.Shipments.Products.ShipSeparately")
                                                </p>
                                            }
                                        </td>
                                        <td style="width: 10%;" class="text-center">
                                            @item.Sku
                                        </td>
                                        <td style="width: 15%;" class="text-center">
                                            @if (item.AllowToChooseWarehouse)
                                            {
                                                if (item.AvailableWarehouses.Count > 0)
                                                {
                                                    <select name="warehouse_@(item.OrderItemId)" id="warehouse_@(item.OrderItemId)" class="form-control">
                                                        @foreach (var warehouse in item.AvailableWarehouses)
                                                        {
                                                            <option value="@warehouse.WarehouseId" data-stock-qty="@warehouse.StockQuantity" data-reserved-qty="@warehouse.ReservedQuantity" data-planned-qty="@warehouse.PlannedQuantity">
                                                                @T("Admin.Orders.Shipments.Products.Warehouse.ChooseQty", warehouse.WarehouseName, warehouse.StockQuantity, warehouse.ReservedQuantity, warehouse.PlannedQuantity)
                                                            </option>
                                                        }
                                                    </select>
                                                }
                                                else
                                                {
                                                    @T("Admin.Orders.Shipments.Products.Warehouse.NotAvailabe")
                                                }
                                            }
                                            else
                                            {
                                                //display warehouses
                                                foreach (var warehouse in item.AvailableWarehouses)
                                                {
                                                    <div>@warehouse.WarehouseName</div>
                                                }
                                            }
                                        </td>
                                        <td style="width: 10%;" class="text-center">
                                            @item.ItemWeight
                                        </td>
                                        <td style="width: 10%;" class="text-center">
                                            @item.ItemDimensions
                                        </td>
                                        <td style="width: 10%;" class="text-center">
                                            @item.QuantityOrdered
                                        </td>
                                        <td style="width: 10%;" class="text-center">
                                            @item.QuantityInAllShipments
                                        </td>
                                        <td style="width: 10%;" class="text-center">
                                            <input name="qtyToAdd@(item.OrderItemId)" type="text" value="@item.QuantityToAdd" id="qtyToAdd@(item.OrderItemId)" class="form-control input-sm" />
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>