Models/Shipping/CutOffTimeListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a cut off time list model
    /// </summary>
    public partial record CutOffTimeListModel : BasePagedListModel<CutOffTimeModel>
    {
    }
}

Models/Shipping/CutOffTimeModel.cs
using System.Collections.Generic;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a cut off time model
    /// </summary>
    public partial record CutOffTimeModel : BaseNopEntityModel, ILocalizedModel<CutOffTimeLocalizedModel>
    {
        #region Ctor

        public CutOffTimeModel()
        {
            Locales = new List<CutOffTimeLocalizedModel>();
            VendorName = string.Empty;
            Name = string.Empty;
        }

        #endregion

        #region Properties

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Vendor")]
        public string VendorName { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.CutOffTimes.Fields.Name")]
        public string Name { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.CutOffTimes.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        public IList<CutOffTimeLocalizedModel> Locales { get; set; }

        #endregion
    }

    public partial class CutOffTimeLocalizedModel : ILocalizedLocaleModel
    {
        public int LanguageId { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.Manager.CutOffTimes.Fields.Name")]
        public string Name { get; set; }
    }
}

Models/Shipping/CutOffTimeSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a cut off times search model
    /// </summary>
    public partial record CutOffTimeSearchModel : BaseSearchModel
    {
        public int VendorId { get; set; }

    }
}

Models/Shipping/DatesRangesSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a dates and ranges search model
    /// </summary>
    public partial record DatesRangesSearchModel : BaseSearchModel
    {
        #region Ctor

        public DatesRangesSearchModel()
        {
            DeliveryDateSearchModel = new DeliveryDateSearchModel();
            ProductAvailabilityRangeSearchModel = new ProductAvailabilityRangeSearchModel();
            CutOffTimeSearchModel = new CutOffTimeSearchModel();
        }

        #endregion

        #region Properties

        public DeliveryDateSearchModel DeliveryDateSearchModel { get; set; }

        public ProductAvailabilityRangeSearchModel ProductAvailabilityRangeSearchModel { get; set; }

        public CutOffTimeSearchModel CutOffTimeSearchModel { get; set; }

        public int VendorId { get; set; }

    #endregion
}
}

Models/Shipping/DeliveryDateListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a delivery date list model
    /// </summary>
    public partial record DeliveryDateListModel : BasePagedListModel<DeliveryDateModel>
    {
    }
}

Models/Shipping/DeliveryDateModel.cs
using System.Collections.Generic;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a delivery date model
    /// </summary>
    public partial record DeliveryDateModel : BaseNopEntityModel, ILocalizedModel<DeliveryDateLocalizedModel>
    {
        #region Ctor

        public DeliveryDateModel()
        {
            Locales = new List<DeliveryDateLocalizedModel>();
            VendorName = string.Empty;
            Name = string.Empty;
        }

        #endregion

        #region Properties

        [NopResourceDisplayName("Plugins.Shipping.Manager.Fields.Vendor")]
        public string VendorName { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Shipping.DeliveryDates.Fields.Name")]
        public string Name { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Shipping.DeliveryDates.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        public IList<DeliveryDateLocalizedModel> Locales { get; set; }

        #endregion
    }

    public partial record DeliveryDateLocalizedModel : ILocalizedLocaleModel
    {
        public int LanguageId { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Shipping.DeliveryDates.Fields.Name")]
        public string Name { get; set; }
    }
}

Models/Shipping/DeliveryDateSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a delivery date search model
    /// </summary>
    public partial record DeliveryDateSearchModel : BaseSearchModel
    {
        public int VendorId { get; set; }

    }
}

Models/Shipping/PickupPointProviderListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a pickup point provider list model
    /// </summary>
    public partial record PickupPointProviderListModel : BasePagedListModel<PickupPointProviderModel>
    {
    }
}

Models/Shipping/PickupPointProviderModel.cs
using Microsoft.AspNetCore.Routing;
using Nop.Web.Framework.Mvc.ModelBinding;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a pickup point provider model
    /// </summary>
    public partial record PickupPointProviderModel : BaseNopModel, IPluginModel
    {
        #region Properties

        [NopResourceDisplayName("Admin.Configuration.Shipping.PickupPointProviders.Fields.FriendlyName")]
        public string FriendlyName { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Shipping.PickupPointProviders.Fields.SystemName")]
        public string SystemName { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Shipping.PickupPointProviders.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Shipping.PickupPointProviders.Fields.IsActive")]
        public bool IsActive { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Shipping.PickupPointProviders.Fields.Logo")]
        public string LogoUrl { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Shipping.PickupPointProviders.Configure")]
        public string ConfigurationUrl { get; set; }

        #endregion
    }
}

Models/Shipping/PickupPointProviderSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a pickup point provider search model
    /// </summary>
    public partial record PickupPointProviderSearchModel : BaseSearchModel
    {
    }
}

Models/Shipping/ProductAvailabilityRangeListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a product availability range list model
    /// </summary>
    public partial record ProductAvailabilityRangeListModel : BasePagedListModel<ProductAvailabilityRangeModel>
    {
    }
}

Models/Shipping/ProductAvailabilityRangeSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Shipping.Manager.Models.Shipping
{
    /// <summary>
    /// Represents a product availability range search model
    /// </summary>
    public partial record ProductAvailabilityRangeSearchModel : BaseSearchModel
    {
        public int VendorId { get; set; }

    }
}

Controllers/ShippingOperationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Nop.Core.Domain.Common;
using Nop.Core.Domain.Shipping;
using Nop.Core.Events;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Plugins;
using Nop.Services.Security;
using Nop.Services.Shipping;
using Nop.Services.Shipping.Date;
using Nop.Services.Shipping.Pickup;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

using Nop.Plugin.Shipping.Manager.Domain;
using Nop.Plugin.Shipping.Manager.Factories;
using Nop.Plugin.Shipping.Manager.Models.Shipping;
using Nop.Plugin.Shipping.Manager.Models.Warehouse;
using Nop.Plugin.Shipping.Manager.Services;

using Nop.Plugin.Apollo.Integrator;

namespace Nop.Plugin.Shipping.Manager.Controllers
{
    public partial class ShippingOperationsController : BaseAdminController
    {

        #region Fields

        protected readonly IAddressService _addressService;
        protected readonly ICountryService _countryService;
        protected readonly ICustomerActivityService _customerActivityService;
        protected readonly IDateRangeService _dateRangeService;
        protected readonly IEventPublisher _eventPublisher;
        protected readonly ILocalizationService _localizationService;
        protected readonly ILocalizedEntityService _localizedEntityService;
        protected readonly INotificationService _notificationService;
        protected readonly IPermissionService _permissionService;
        protected readonly IPickupPluginManager _pickupPluginManager;
        protected readonly ISettingService _settingService;
        protected readonly IShippingOperationsModelFactory _shippingOperationsModelFactory;
        protected readonly IShippingPluginManager _shippingPluginManager;
        protected readonly IShippingService _shippingService;
        protected readonly ShippingSettings _shippingSettings;
        protected readonly ICarrierService _carrierService;
        protected readonly IShippingManagerService _shippingManagerService;

        #endregion

        #region Ctor

        public ShippingOperationsController(IAddressService addressService,
            ICountryService countryService,
            ICustomerActivityService customerActivityService,
            IDateRangeService dateRangeService,
            IEventPublisher eventPublisher,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IPickupPluginManager pickupPluginManager,
            ISettingService settingService,
            IShippingOperationsModelFactory shippingOperationsModelFactory,
            IShippingPluginManager shippingPluginManager,
            IShippingService shippingService,
            ShippingSettings shippingSettings,
            ICarrierService carrierService,
            IShippingManagerService shippingManagerService)
        {
            _addressService = addressService;
            _countryService = countryService;
            _customerActivityService = customerActivityService;
            _dateRangeService = dateRangeService;
            _eventPublisher = eventPublisher;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _pickupPluginManager = pickupPluginManager;
            _settingService = settingService;
            _shippingOperationsModelFactory = shippingOperationsModelFactory;
            _shippingPluginManager = shippingPluginManager;
            _shippingService = shippingService;
            _shippingSettings = shippingSettings;
            _carrierService = carrierService;
            _shippingManagerService = shippingManagerService;
        }

        #endregion

        #region Utilities

        protected virtual async Task UpdateLocalesAsync(ShippingMethod shippingMethod, ShippingMethodModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(shippingMethod, x => x.Name, localized.Name, localized.LanguageId);
                await _localizedEntityService.SaveLocalizedValueAsync(shippingMethod, x => x.Description, localized.Description, localized.LanguageId);
            }
        }

        protected virtual async Task UpdateLocalesAsync(DeliveryDate deliveryDate, DeliveryDateModel model)
        {
            foreach (var localized in model.Locales)
                await _localizedEntityService.SaveLocalizedValueAsync(deliveryDate, x => x.Name, localized.Name, localized.LanguageId);
        }

        protected virtual async Task UpdateLocalesAsync(ProductAvailabilityRange productAvailabilityRange, ProductAvailabilityRangeModel model)
        {
            foreach (var localized in model.Locales)
                await _localizedEntityService.SaveLocalizedValueAsync(productAvailabilityRange, x => x.Name, localized.Name, localized.LanguageId);
        }

        protected virtual async Task UpdateLocalesAsync(CutOffTime cutOffTime, CutOffTimeModel model)
        {
            foreach (var localized in model.Locales)
                await _localizedEntityService.SaveLocalizedValueAsync(cutOffTime, x => x.Name, localized.Name, localized.LanguageId);
        }

        #endregion

        #region Pickup point providers

        public virtual async Task<IActionResult> PickupPointProviders()
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Manage))
                return AccessDeniedView();

            //prepare model
            var model = _shippingOperationsModelFactory.PreparePickupPointProviderSearchModel(new PickupPointProviderSearchModel());

            return View("~/Plugins/SSI.Shipping.Manager/Views/Shipping/PickupPointProviders.cshtml", model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> PickupPointProviders(PickupPointProviderSearchModel searchModel)
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Manage))
                return AccessDeniedView();

            //prepare model
            var model = await _shippingOperationsModelFactory.PreparePickupPointProviderListModelAsync(searchModel);

            return Json(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> PickupPointProviderUpdate(PickupPointProviderModel model)
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Manage))
                return AccessDeniedView();

            var pickupPointProvider = await _pickupPluginManager.LoadPluginBySystemNameAsync(model.SystemName);
            if (_pickupPluginManager.IsPluginActive(pickupPointProvider))
            {
                if (!model.IsActive)
                {
                    //mark as disabled
                    _shippingSettings.ActivePickupPointProviderSystemNames.Remove(pickupPointProvider.PluginDescriptor.SystemName);
                    await _settingService.SaveSettingAsync(_shippingSettings);
                }
            }
            else
            {
                if (model.IsActive)
                {
                    //mark as active
                    _shippingSettings.ActivePickupPointProviderSystemNames.Add(pickupPointProvider.PluginDescriptor.SystemName);
                    await _settingService.SaveSettingAsync(_shippingSettings);
                }
            }

            var pluginDescriptor = pickupPointProvider.PluginDescriptor;
            pluginDescriptor.DisplayOrder = model.DisplayOrder;

            //update the description file
            pluginDescriptor.Save();

            //raise event
            await _eventPublisher.PublishAsync(new PluginUpdatedEvent(pluginDescriptor));

            return new NullJsonResult();
        }

        #endregion

        #region Shipping methods

        public virtual async Task<IActionResult> Methods()
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Operate))
                return AccessDeniedView();

            //prepare model
            var model = await _shippingOperationsModelFactory.PrepareShippingMethodSearchModelAsync(new ShippingMethodSearchModel());

            return View("~/Plugins/SSI.Shipping.Manager/Views/Shipping/Methods.cshtml", model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> Methods(ShippingMethodSearchModel searchModel)
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Operate))
                return AccessDeniedView();

            //prepare model
            var model = await _shippingOperationsModelFactory.PrepareShippingMethodListModelAsync(searchModel);

            return Json(model);
        }

        public virtual async Task<IActionResult> CreateMethod()
        {
            if (!await _shippingManagerService.AuthorizeAsync(SystemHelper.AccessMode.Operate))
                return AccessDeniedView();

            //prepare model
            var model = await _shippingOperationsModelFactory.PrepareShippingMethodModelAsync(new ShippingMethodModel(), null);

            return View("~/Plugins/SSI.Shipping.Manager/Views/Shipping/CreateMethod.cshtml", model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]

Views/Shipping/CreateCutOffTime.cshtml
@model CutOffTimeModel

@{
    Layout = "_AdminLayout";

    //page title
    ViewBag.Title = T("Nop.Plugins.Shipping.Manager.CutOffTimes.AddNew").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Nop.Plugins.Shipping.Manager.DatesAndRanges");
}

<form asp-controller="ShippingOperations" asp-action="CreateCutOffTime" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Plugins.Shipping.Manager.CutOffTimes.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="DatesAndRanges">@T("Plugins.Shipping.Manager.CutOffTimes.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = ShippingManagerWidgetZones.CutOffTimeDetailsButtons })
        </div>
    </div>
    <div class="content">
        @await Component.InvokeAsync("VendorScopeConfiguration")
        @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/Shipping/_CreateOrUpdateCutOffTime.cshtml")
    </div>
</form>

Views/Shipping/CreateProductAvailabilityRange.cshtml
@model ProductAvailabilityRangeModel

@{
    Layout = "_AdminLayout";

    //page title
    ViewBag.Title = T("Admin.Configuration.Shipping.ProductAvailabilityRanges.AddNew").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Nop.Plugins.Shipping.Manager.DatesAndRanges");
}

<form asp-controller="ShippingOperations" asp-action="CreateProductAvailabilityRange" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Shipping.ProductAvailabilityRanges.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="DatesAndRanges">@T("Admin.Configuration.Shipping.ProductAvailabilityRanges.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductAvailabilityRangeDetailsButtons })
        </div>
    </div>
    <div class="content">
        @await Component.InvokeAsync("VendorScopeConfiguration")
        @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/Shipping/_CreateOrUpdateProductAvailabilityRange.cshtml")
    </div>
</form>

Views/Shipping/CreateWarehouse.cshtml
@model WarehouseModel

@{
    Layout = "_AdminLayout";
    
    //page title
    ViewBag.Title = T("Admin.Configuration.Shipping.Warehouses.AddNew").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Nop.Plugins.Shipping.Manager.Warehouses");
}

<form asp-controller="ShippingOperations" asp-action="CreateWarehouse" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Shipping.Warehouses.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="Warehouses">@T("Admin.Configuration.Shipping.Warehouses.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.WarehouseDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/Shipping/_CreateOrUpdateWarehouse.cshtml")
</form>

Views/Shipping/EditCutOffTime.cshtml
@model CutOffTimeModel

@{
    Layout = "_AdminLayout";
    
    //page title
    ViewBag.Title = T("Nop.Plugins.Shipping.Manager.CutOffTimes.EditCutOffTimeDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Nop.Plugins.Shipping.Manager.DatesAndRanges");
}

<form asp-controller="ShippingOperations" asp-action="EditCutOffTime" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Plugins.Shipping.Manager.CutOffTimes.EditCutOffTimeDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="DatesAndRanges">@T("Plugins.Shipping.Manager.CutOffTimes.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="cut-off-time-delete" class="btn bg-red">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = ShippingManagerWidgetZones.CutOffTimeDetailsButtons, additionalData = Model })
        </div>
    </div>
    <div class="content">
        @await Component.InvokeAsync("VendorScopeConfiguration")
        @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/Shipping/_CreateOrUpdateCutOffTime.cshtml")
    </div>
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="cut-off-time-delete" asp-action="DeleteCutOffTime" />

Views/Shipping/EditWarehouse.cshtml
@model WarehouseModel

@{
    Layout = "_AdminLayout";

    //page title
    ViewBag.Title = T("Admin.Configuration.Shipping.Warehouses.EditWarehouseDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Nop.Plugins.Shipping.Manager.Warehouses");
}

<form asp-controller="ShippingOperations" asp-action="EditWarehouse" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Shipping.Warehouses.EditWarehouseDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="Warehouses">@T("Admin.Configuration.Shipping.Warehouses.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="warehouse-delete" class="btn bg-red">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.WarehouseDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/SSI.Shipping.Manager/Views/Shipping/_CreateOrUpdateWarehouse.cshtml")
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="warehouse-delete" asp-action="DeleteWarehouse" />

Views/Shipping/Restrictions.cshtml
@model ShippingMethodRestrictionModel

@{
    Layout = "_AdminLayout";

    //page title
    ViewBag.Title = T("Admin.Configuration.Shipping.Restrictions").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Nop.Plugins.Shipping.Manager.Methods");
}


<form asp-controller="ShippingOperations" asp-action="Restrictions" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Shipping.Restrictions")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ShippingRestrictionListButtons })
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            <div class="cards-group">
                <div class="card card-default">
                    <div class="card-body" style="overflow-x: auto;">
                        <p>@T("Admin.Configuration.Shipping.Restrictions.Description")</p>
                        @if (Model.AvailableCountries.Count == 0)
                        {
                            <text>No countries defined</text>
                        }
                        else if (Model.AvailableShippingMethods.Count == 0)
                        {
                            <text>No shipping methods available</text>
                        }
                        else
                        {
                            <script>
                                $(document).ready(function () {
                                    @foreach (var sm in Model.AvailableShippingMethods)
                                    {
                                        <text>
                                            $('#selectall-@(sm.Id)').click(function () {
                                                $('.restrict_@(sm.Id)').attr('checked', $(this).is(':checked')).change();
                                            });
                                        </text>
                                    }
                                });
                            </script>

                            <table class="table table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <th scope="col">
                                            <strong>@T("Admin.Configuration.Shipping.Restrictions.Country")</strong>
                                        </th>
                                        @foreach (var sm in Model.AvailableShippingMethods)
                                        {
                                            <th scope="col">
                                                <strong>@sm.Name</strong>
                                                <input type="checkbox" id="selectall-@(sm.Id)" />
                                            </th>
                                        }
                                    </tr>
                                </thead>
                                <tbody>                                 
                                    @foreach (var c in Model.AvailableCountries)
                                    {
                                        <tr>
                                            <td>
                                                <span>@c.Name</span>
                                            </td>
                                            @foreach (var sm in Model.AvailableShippingMethods)
                                            {
                                                var restricted = Model.Restricted.ContainsKey(c.Id) && Model.Restricted[c.Id][sm.Id];
                                                <td>
                                                    <input id="restrict_@(sm.Id)" class="restrict_@(sm.Id)" type="checkbox" value="@(c.Id)" name="restrict_@(sm.Id)" @(restricted ? " checked=checked" : null) />
                                                </td>
                                            }
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>